[auth.email.template.recovery]
subject = "Restablece tu contraseña · Eclipse"
content_path = "./supabase/templates/recovery.html"

[functions.create-payment-intent-v2]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.stripe-connect-create-account]
verify_jwt = false

[functions.stripe-connect-onboarding-link]
verify_jwt = false

[functions.stripe-connect-refresh-status]
verify_jwt = false

[functions.stripe-get-account-stats]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.apple-wallet-generator]
verify_jwt = false

[functions.generate-wallet-pass]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.auth-redirect]
verify_jwt = false
