-- Disposable database regression. Never run the fixture or this file on a Supabase project.
\set ON_ERROR_STOP on
begin;
create temp table operation_results(label text);
create function pg_temp.assert(ok boolean,label text) returns void language plpgsql as $$begin
 if ok is distinct from true then raise exception 'OPERATIONS TEST FAILED: %',label; end if;
 insert into operation_results values(label);
end$$;
create function pg_temp.payment(buyer uuid,event uuid,kind text default 'event_ticket',n integer default 2,cents bigint default 1500) returns uuid language plpgsql as $$declare p uuid:=gen_random_uuid();begin
 insert into public.payment_transactions(id,user_id,kind,metadata) values(p,buyer,kind,jsonb_build_object('event_id',event,'quantity',n,'discounted_total_cents',cents));
 update public.payment_transactions set status='fulfilled' where id=p;
 return p;
end$$;
do $$
declare buyer uuid:=gen_random_uuid(); org uuid:=gen_random_uuid(); other_org uuid:=gen_random_uuid(); adm uuid:=gen_random_uuid(); ev uuid:=gen_random_uuid(); p uuid; vp uuid; late uuid;
 claim uuid:=gen_random_uuid(); admission uuid:=gen_random_uuid(); vip uuid:=gen_random_uuid(); o notification_private.outbox%rowtype; earlier notification_private.outbox%rowtype;
 n integer; result jsonb; denied boolean; before_count integer; legacy_count integer; old_state text;
begin
 insert into auth.users(id,email,email_confirmed_at) values(buyer,'buyer-ops@example.invalid',now()),(org,'org-ops@example.invalid',now()),(other_org,'other-ops@example.invalid',now()),(adm,'admin-ops@example.invalid',now());
 insert into public.profiles(id,role) values(buyer,'attendee'),(org,'organizer'),(other_org,'organizer'),(adm,'admin');
 insert into public.events(id,creator_id,title,event_date,end_datetime) values(ev,org,'Fixture nightlife',now()+interval '3 days',now()+interval '3 days 12 hours');
 select count(*) into legacy_count from public.notification_deliveries;
 perform pg_temp.payment(buyer,ev);
 perform pg_temp.assert(not exists(select 1 from notification_private.sale_facts),'capture disabled records no sales');
 update notification_private.config set capture_enabled=true,cutover_at=now()+interval '10 days';
 perform pg_temp.payment(buyer,ev);
 perform pg_temp.assert(not exists(select 1 from notification_private.sale_facts),'operations gate independently disabled');
 insert into public.notifications(user_id,type,title) values(org,'organizer_new_sale','Legacy retained');
 perform pg_temp.assert(exists(select 1 from public.notifications where user_id=org and title='Legacy retained'),'legacy organizer producer retained while operations disabled');
 update notification_private.config set operations_enabled=true;
 insert into public.notifications(user_id,type,title) values(org,'organizer_new_sale','Legacy suppressed');
 perform pg_temp.assert(not exists(select 1 from public.notifications where title='Legacy suppressed'),'legacy sales suppressed only when replacement enabled');
 p:=pg_temp.payment(buyer,ev,'event_ticket',3,1500); vp:=pg_temp.payment(buyer,ev,'vip_table',8,10000);
 perform pg_temp.assert((select count(*)=2 from notification_private.sale_facts),'each primary payment creates one durable fact');
 perform pg_temp.assert((select units=1 from notification_private.sale_facts where source_id=vp),'whole VIP table never counts guest capacity as sales');
 perform pg_temp.assert((select mode='grouped' and due_at>now() and due_at<=now()+interval '15 minutes' from notification_private.sale_facts where source_id=p),'default grouping uses bounded fifteen minute window');
 perform pg_temp.assert(notification_private.prepare_sales()=0,'future sales window is not emitted early');
 update notification_private.sale_facts set due_at=now()-interval '1 minute' where processed_at is null;
 perform pg_temp.assert(notification_private.prepare_sales()=1,'one digest combines admission and VIP sales');
 select * into o from notification_private.outbox where user_id=org and kind='organizer.sales_digest';
 perform pg_temp.assert(o.data->>'orders'='2' and o.data->>'ticket_units'='3' and o.data->>'vip_tables'='1','digest reports order and product counts separately');
 perform pg_temp.assert(o.data->>'product_subtotal_cents'='11500' and o.body like '%No es una liquidación%','subtotal is not represented as payout');
 perform pg_temp.assert(not (o.data ? 'buyer_id') and not (o.data ? 'email'),'sales digest carries no customer identity');
 update public.payment_transactions set status='created' where id=p;
 update public.payment_transactions set status='fulfilled' where id=p;
 perform pg_temp.assert((select count(*)=2 from notification_private.sale_facts),'status replay cannot double capture a sale');
 perform pg_temp.assert(notification_private.prepare_sales()=0,'prepared sale facts cannot double count');
 late:=pg_temp.payment(buyer,ev,'event_ticket',1,1200);
 update notification_private.sale_facts set due_at=(o.data->>'period_end')::timestamptz where source_id=late;
 perform pg_temp.assert(notification_private.prepare_sales()=1,'late fact in previously processed bucket is not lost');
 perform pg_temp.assert((select count(*)=2 and count(distinct event_key)=2 from notification_private.outbox where user_id=org and kind='organizer.sales_digest'),'late digest uses a distinct membership identity');
 p:=pg_temp.payment(buyer,ev); update public.payment_transactions set status='refunded' where id=p;
 update notification_private.sale_facts set due_at=now()-interval '1 minute' where source_id=p;
 perform pg_temp.assert(notification_private.prepare_sales()=0,'refunded payment excluded before aggregation');
 perform pg_temp.assert((select processed_at is not null from notification_private.sale_facts where source_id=p),'ineligible fact does not clog the queue');
 insert into public.notification_preferences_v2(user_id,role,sales_mode,quiet_enabled) values(org,'organizer','immediate',false);
 p:=pg_temp.payment(buyer,ev);
 perform pg_temp.assert(notification_private.prepare_sales()=1,'immediate mode is due without waiting');
 select * into o from notification_private.outbox where user_id=org and kind='organizer.sales_instant' order by id limit 1;
 perform pg_temp.assert(o.channels=array['push'],'instant sales do not add unsolicited email');
 update public.notification_preferences_v2 set sales_mode='grouped',vip_sales_immediate=true where user_id=org;
 vp:=pg_temp.payment(buyer,ev,'vip_table',12,20000);
 perform pg_temp.assert((select mode='immediate' and units=1 from notification_private.sale_facts where source_id=vp),'VIP immediate override is opt-in and counts one table');
 perform pg_temp.assert(notification_private.prepare_sales()=1,'VIP override can emit immediately');
 update public.notification_preferences_v2 set sales_mode='off' where user_id=org;
 perform pg_temp.assert(not notification_private.channel_allowed(o,'push'),'changing preferences suppresses queued sales channel');
 p:=pg_temp.payment(buyer,ev);
 update notification_private.sale_facts set due_at=now()-interval '1 minute' where source_id=p;
 perform pg_temp.assert(notification_private.prepare_sales()=1,'history-only mode still records an inbox digest');
 perform pg_temp.assert(exists(select 1 from notification_private.outbox where user_id=org and kind='organizer.sales_digest' and cardinality(channels)=0),'history-only digest has no remote channels');
 update public.notification_preferences_v2 set sales_mode='immediate' where user_id=org;
 insert into public.tickets(user_id,event_id,total_price,free_claim_id) values(buyer,ev,0,claim),(buyer,ev,0,claim);
 perform pg_temp.assert((select count(*)=2 and bool_and(mode='grouped') from notification_private.sale_facts where order_key='free:'||claim),'free invitation facts grouped even in immediate mode');
 update notification_private.sale_facts set due_at=now()-interval '2 minutes' where order_key='free:'||claim;
 perform pg_temp.assert(notification_private.prepare_sales()=1,'one free-claim digest prepared');
 perform pg_temp.assert(exists(select 1 from notification_private.outbox where user_id=org and data->>'invitations'='2' and data->>'orders'='1' and data->>'product_subtotal_cents'='0'),'free group reports two invitations and one claim, not paid sales');
 insert into public.tickets(user_id,event_id,total_price,sold_by_worker_id,quantity) values(buyer,ev,30,gen_random_uuid(),3);
 perform pg_temp.assert(exists(select 1 from notification_private.sale_facts where product_kind='box_office' and mode='grouped' and units=3 and amount_cents=3000),'linked box-office units are grouped separately');
 p:=pg_temp.payment(buyer,ev,'resale_ticket',1,1000);
 perform pg_temp.assert(not exists(select 1 from notification_private.sale_facts where source_id=p),'resale remains excluded');
 perform pg_temp.assert(notification_private.nonnegative_integer('not money') is null and notification_private.nonnegative_integer('-1') is null and notification_private.nonnegative_integer('500')=500,'malformed subtotal does not become invented revenue');
 p:=pg_temp.payment(buyer,ev,'event_ticket',1,null);
 perform notification_private.prepare_sales();
 perform pg_temp.assert(exists(select 1 from notification_private.outbox where kind='organizer.sales_instant' and data->'product_subtotal_cents'='null'::jsonb and body not like '%Importe de productos:%'),'unknown subtotal is omitted rather than shown as zero');
 -- Stock transitions, no historical scan of existing catalog.
 insert into public.event_ticket_types(id,event_id,name,quantity,sold) values(admission,ev,'General',100,0);
 insert into public.reservados_vip(id,event_id,name,quantity_available) values(vip,ev,'Mesa principal',4);
 perform pg_temp.assert(not exists(select 1 from notification_private.outbox where kind='organizer.stock_alert'),'creating products emits no low-stock alert');
 update public.event_ticket_types set sold=80 where id=admission;
 select * into o from notification_private.outbox where kind='organizer.stock_alert' and data->>'product_id'=admission::text;
 perform pg_temp.assert(o.data->>'band'='20' and notification_private.is_current(o),'20 percent threshold emits current admission alert');
 update public.event_ticket_types set sold=81 where id=admission;
 perform pg_temp.assert((select count(*)=1 from notification_private.outbox where kind='organizer.stock_alert'),'no push after each sale within the same band');
 update public.event_ticket_types set name='General edited' where id=admission;
 perform pg_temp.assert(notification_private.is_current(o),'renaming keeps band and emits no duplicate');
 update public.event_ticket_types set sold=95 where id=admission;
 perform pg_temp.assert(not notification_private.is_current(o),'more urgent stock band supersedes stale pending alert');
 perform pg_temp.assert(exists(select 1 from notification_private.outbox where kind='organizer.stock_alert' and data->>'band'='5'),'five percent threshold exists');
 update public.event_ticket_types set sold=100 where id=admission;
 select * into o from notification_private.outbox where kind='organizer.stock_alert' and data->>'product_id'=admission::text and data->>'band'='0';
 perform pg_temp.assert(o.priority='high' and notification_private.is_current(o),'sold out gets current high priority');
 select count(*) into before_count from notification_private.outbox where kind='organizer.stock_alert';
 update public.event_ticket_types set quantity=120 where id=admission;
 perform pg_temp.assert(not notification_private.is_current(o),'restocking invalidates sold-out queued notification');
 perform pg_temp.assert((select count(*)=before_count from notification_private.outbox where kind='organizer.stock_alert'),'restock itself emits no push');
 update public.event_ticket_types set sold=120 where id=admission;
 perform pg_temp.assert(exists(select 1 from notification_private.outbox where kind='organizer.stock_alert' and data->>'product_id'=admission::text and data->>'band'='0' and cardinality(channels)=0),'repeated same-band crossing within hour is inbox-only');
 update public.reservados_vip set quantity_available=2 where id=vip;
 perform pg_temp.assert(exists(select 1 from notification_private.outbox where kind='organizer.stock_alert' and data->>'product_id'=vip::text and data->>'band'='2' and body like '%dos mesas%'),'VIP last two uses absolute count, not guest capacity');
 update public.reservados_vip set quantity_available=1 where id=vip;
 perform pg_temp.assert(exists(select 1 from notification_private.outbox where kind='organizer.stock_alert' and data->>'product_id'=vip::text and data->>'band'='1'),'VIP last table alert');
 update public.reservados_vip set quantity_available=0 where id=vip;
 select * into o from notification_private.outbox where kind='organizer.stock_alert' and data->>'product_id'=vip::text and data->>'band'='0';
 perform pg_temp.assert(notification_private.is_current(o),'VIP zero inventory alert');
 update public.notification_preferences_v2 set stock_alerts=false where user_id=org;
 perform pg_temp.assert(not notification_private.channel_allowed(o,'push'),'stock-specific opt-out suppresses delivery');
 update public.notification_preferences_v2 set stock_alerts=true,operations=false where user_id=org;
 perform pg_temp.assert(not notification_private.channel_allowed(o,'push'),'general operation opt-out takes precedence');
 update public.notification_preferences_v2 set operations=true where user_id=org;
 update public.reservados_vip set is_active=false where id=vip;
 perform pg_temp.assert(not notification_private.is_current(o),'disabled product suppresses pending availability alert');
 update public.reservados_vip set is_active=true where id=vip;
 perform pg_temp.assert(not notification_private.is_current(o),'reenabling does not revive stale alert');
 delete from public.reservados_vip where id=vip;
 perform pg_temp.assert((select not active from notification_private.stock_state where product_id=vip),'deletion revokes private stock state');
 select * into o from notification_private.outbox where kind='organizer.sales_digest' and user_id=org limit 1;
 update public.events set creator_id=other_org where id=ev;
 perform pg_temp.assert(not notification_private.is_current(o),'former organizer cannot receive event sales after ownership change');
 update public.events set creator_id=org where id=ev;
 update notification_private.config set operations_enabled=false;
 perform pg_temp.assert(not notification_private.is_current(o),'closing operations gate suppresses already queued operation notices');
 update notification_private.config set operations_enabled=true;
 -- Security boundaries and heartbeat: no network or secret introspection.
 perform pg_temp.assert(not has_table_privilege('authenticated','notification_private.sale_facts','SELECT') and not has_table_privilege('anon','notification_private.stock_state','SELECT'),'clients cannot inspect private operational tables');
 perform pg_temp.assert(not has_function_privilege('authenticated','public.record_notification_worker_tick_v2(text,integer,integer,boolean,boolean)','EXECUTE'),'client cannot fabricate worker health');
 perform pg_temp.assert(has_function_privilege('service_role','public.record_notification_worker_tick_v2(text,integer,integer,boolean,boolean)','EXECUTE'),'service can record execution');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',buyer,'role','authenticated')::text,true);
 denied:=false; begin perform public.notification_health_v2(); exception when insufficient_privilege then denied:=true; end;
 perform pg_temp.assert(denied,'non-admin cannot inspect health aggregates');
 perform set_config('request.jwt.claims','{}',true);
 denied:=false; begin perform public.notification_health_v2(); exception when insufficient_privilege then denied:=true; end;
 perform pg_temp.assert(denied,'null identity fails closed for health');
 perform public.record_notification_worker_tick_v2('running',0,0,true,false);
 perform public.record_notification_worker_tick_v2('disabled',0,0,true,false);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',adm,'role','authenticated')::text,true);
 result:=public.notification_health_v2();
 perform pg_temp.assert(result->'worker'->>'last_status'='disabled' and result->'worker'->>'last_completed_at' is not null,'worker heartbeat distinguishes disabled from successful delivery');
 perform pg_temp.assert((result->>'pilot_recipient_count')::integer=0 and not result ? 'allowed_recipients' and not result ? 'tokens','health exposes counts only, not recipients or tokens');
 perform pg_temp.assert(result->>'live_delivery_enabled'='false' and jsonb_array_length(result->'by_channel')=0,'health reflects closed pilot and no delivery');
 update public.profiles set is_suspended=true where id=adm;
 denied:=false; begin perform public.notification_health_v2(); exception when insufficient_privilege then denied:=true; end;
 perform pg_temp.assert(denied,'suspended administrator denied');
 update public.profiles set is_suspended=false where id=adm;
 denied:=false; begin perform public.record_notification_worker_tick_v2('sent'); exception when others then denied:=true; end;
 perform pg_temp.assert(denied,'invalid heartbeat state rejected');
 perform pg_temp.assert(not (select live_delivery_enabled from notification_private.config),'all tests retain closed remote delivery gate');
end$$;
select count(*) as passed from operation_results;
rollback;
