const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const root=path.join(__dirname,'../..');
function load(file,imports={},extra={}){const exp={};const result=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}});vm.runInNewContext(result.outputText,{exports:exp,require:n=>{if(n in imports)return imports[n];throw Error('Unexpected import '+n);},console,Promise,Date,...extra});return exp;}
const routing=load('lib/notificationRouting.ts');const model=load('lib/notificationSchema.ts');
const user='71000000-0000-4000-8000-000000000001',id='72000000-0000-4000-8000-000000000001';
test('push cannot choose a URL or privileged route',()=>{for(const data of [{url:'/(admin)/users'}, {type:'admin',eventId:'../../admin'},{notification_id:'bad?role=admin'},null]) assert.equal(routing.notificationInboxRoute(data).pathname,'/notifications');});
test('valid push opens only an owner-scoped inbox detail',()=>{const route=routing.notificationInboxRoute({notification_id:id,url:'https://bad.invalid'});assert.equal(route.params.notificationId,id);assert.equal(route.pathname,'/notifications');});
test('another user notification has no action',()=>assert.equal(routing.notificationAction({user_id:'other',type:'order.vip_confirmed'},user,'organizer'),null));
test('organizer CTA requires actual organizer profile',()=>{const row={user_id:user,role:'organizer',type:'organizer.verification_approved'};assert.equal(routing.notificationAction(row,user,'attendee'),null);assert.equal(routing.notificationAction(row,user,'organizer').path,'/(creator)/');});
test('unknown or withdrawn event uses no fabricated route',()=>assert.equal(routing.notificationAction({user_id:user,type:'event.cancelled',event_id:id},user),null));
test('event identifier is validated before routing',()=>{assert.equal(routing.notificationAction({user_id:user,type:'event.venue_changed',event_id:'../../admin'},user),null);assert.equal(routing.notificationAction({user_id:user,type:'event.venue_changed',event_id:id},user).path,'/(tabs)/event/'+id);});
test('delivery status does not make core notification read',()=>{assert.equal(model.normalizeNotificationRow({notification_version:2,status:'read',read:false}).read,false);assert.equal(model.normalizeNotificationRow({notification_version:2,read_at:'now'}).read,true);assert.equal(model.normalizeNotificationRow({status:'read'}).read,true);});
function pushFixture(){let current=user;const calls=[],storage=new Map();const Notifications={getPermissionsAsync:async()=>({granted:false,canAskAgain:true}),requestPermissionsAsync:async()=>{calls.push('prompt');return {granted:true};},setNotificationChannelAsync:async()=>{calls.push('channel');},getExpoPushTokenAsync:async()=>({data:'ExpoPushToken['+'fixture'.repeat(3)+']'}),dismissAllNotificationsAsync:async()=>{},clearLastNotificationResponseAsync:async()=>{calls.push('clear-last');},setBadgeCountAsync:async()=>{},setNotificationHandler:()=>{},addPushTokenListener:()=>({remove(){}}),AndroidImportance:{DEFAULT:3}};
const api={auth:{getSession:async()=>({data:{session:{user:{id:current}}}})},rpc:async(name,args)=>{calls.push({name,args});return {error:null};}};
const asyncStorage={getItem:async k=>storage.get(k)??null,setItem:async(k,v)=>storage.set(k,v),removeItem:async k=>storage.delete(k)};
const lib=load('lib/notifications.ts',{'expo-notifications':Notifications,'react-native':{Platform:{OS:'android'}},'expo-constants':{default:{easConfig:{projectId:id}}},'@react-native-async-storage/async-storage':{default:asyncStorage},'@/lib/supabase':{supabase:api}});
return {lib,calls,Notifications,api,current:v=>{current=v;},storage};}
test('automatic registration never opens OS permission prompt',async()=>{const f=pushFixture();f.lib.setNotificationUser(user);assert.equal(await f.lib.registerForPushNotifications(user),false);assert.ok(!f.calls.includes('prompt'));});
test('explicit opt-in creates Android channel before prompt and binds expected user',async()=>{const f=pushFixture();f.lib.setNotificationUser(user);assert.equal(await f.lib.registerForPushNotifications(user,{requestPermission:true}),true);assert.ok(f.calls.indexOf('channel')<f.calls.indexOf('prompt'));const rpc=f.calls.find(c=>c.name==='register_core_push_token');assert.equal(rpc.args.p_user,user);assert.equal(rpc.args.p_project,id);});
test('first login preserves cold-start notification response for navigation',async()=>{const f=pushFixture();f.lib.setNotificationUser(user);await f.lib.registerForPushNotifications(user);assert.ok(!f.calls.includes('clear-last'));});
test('stale token response after account switch cannot register for new account',async()=>{const f=pushFixture();f.Notifications.getPermissionsAsync=async()=>({granted:true});f.Notifications.getExpoPushTokenAsync=async()=>{f.lib.setNotificationUser('another-user');f.current('another-user');return {data:'fake'};};f.lib.setNotificationUser(user);assert.equal(await f.lib.registerForPushNotifications(user),false);assert.ok(!f.calls.some(c=>c.name==='register_core_push_token'));});
test('logout revokes registration without passing token to logs',async()=>{const f=pushFixture();f.lib.setNotificationUser(user);await f.lib.registerForPushNotifications(user,{requestPermission:true});await f.lib.unregisterForPushNotifications(user);const revoke=f.calls.find(c=>c.name==='unregister_core_push_token');assert.equal(revoke.args.p_user,user);assert.equal(f.storage.size,0);});
test('production UI has no privileged dispatcher invocation',()=>{for(const file of ['app/_layout.tsx','lib/EventContext.tsx'])assert.ok(!fs.readFileSync(path.join(root,file),'utf8').includes("'dispatch-notifications'"));});
test('inbox keeps independent unread count and uses state RPC, never deletes evidence',()=>{const text=fs.readFileSync(path.join(root,'lib/NotificationContext.tsx'),'utf8');assert.ok(text.includes("'core_notification_unread_count'"));assert.ok(text.includes("'set_core_notification_state'"));assert.ok(!text.includes('.delete()'));assert.ok(text.includes('identity.current.epoch'));});

test('cursor preserves PostgreSQL microseconds and rejects filter injection',()=>{assert.equal(routing.notificationCursorIsValid('2026-10-07T19:46:02.123456+00:00'),true);assert.equal(routing.notificationCursorIsValid('2026-10-07T19:46:02Z),user_id.neq.any'),false);const src=fs.readFileSync(path.join(root,'lib/NotificationContext.tsx'),'utf8');assert.ok(src.includes('const cursor = last.created_at;'));});
