-- Eclipse Staging only. Coupon writes are rolled back in a subtransaction.
-- No payments, balances, ticket/stock writes, providers or user promotion.
BEGIN;
SET LOCAL lock_timeout='3s';
SET LOCAL statement_timeout='30s';
DO $qa$
DECLARE e uuid; owner_id uuid; admission uuid; vip uuid; stranger uuid; c public.discount_codes; tx public.payment_transactions; result public.discount_codes; checks integer:=0; failed boolean; original_codes bigint;
BEGIN
 ASSERT NOT (SELECT capture_enabled OR operations_enabled OR live_delivery_enabled OR allow_all_recipients FROM notification_private.config), 'Notification gates must be closed';
 SELECT count(*) INTO original_codes FROM public.discount_codes;
 SELECT ev.id,ev.creator_id,tt.id,v.id INTO e,owner_id,admission,vip FROM public.events ev JOIN public.event_ticket_types tt ON tt.event_id=ev.id JOIN public.reservados_vip v ON v.event_id=ev.id WHERE tt.is_active AND tt.deleted_at IS NULL AND v.is_active AND v.deleted_at IS NULL LIMIT 1;
 SELECT id INTO stranger FROM public.profiles WHERE id<>owner_id AND role='attendee' LIMIT 1;
 ASSERT e IS NOT NULL AND stranger IS NOT NULL, 'Existing staging catalog and attendee are required';
 BEGIN
  PERFORM set_config('request.jwt.claim.sub','',true); PERFORM set_config('request.jwt.claims','{}',true);
  INSERT INTO public.discount_codes(event_id,creator_id,code,discount_type,discount_value,min_tickets,valid_from,is_active) VALUES(e,owner_id,'RC_QA_'||replace(gen_random_uuid()::text,'-',''),'percentage',20,1,now()-interval '1 hour',true) RETURNING * INTO c;
  ASSERT c.applicability='tickets' AND cardinality(c.ticket_type_ids)=0 AND cardinality(c.vip_reservado_ids)=0, 'Legacy defaults'; checks:=checks+1;
  ASSERT private.discount_rule_error(c,e,'event_ticket',admission,1) IS NULL, 'Admission allowed'; checks:=checks+1;
  ASSERT private.discount_rule_error(c,e,'vip_table',vip,1) IS NOT NULL, 'Legacy VIP denied'; checks:=checks+1;
  ASSERT private.discount_rule_error(c,gen_random_uuid(),'event_ticket',admission,1) IS NOT NULL, 'Foreign event denied'; checks:=checks+1;
  failed:=false; BEGIN PERFORM public.validate_discount_code_for_product(c.code,e,1,admission,NULL); EXCEPTION WHEN insufficient_privilege THEN failed:=true; END;
  ASSERT failed, 'Anonymous validation denied'; checks:=checks+1;
  PERFORM set_config('request.jwt.claim.sub',stranger::text,true); PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',stranger,'role','authenticated')::text,true);
  failed:=false; BEGIN UPDATE public.discount_codes SET applicability='all' WHERE id=c.id; EXCEPTION WHEN insufficient_privilege THEN failed:=true; END;
  ASSERT failed, 'Foreign organizer write denied'; checks:=checks+1;
  PERFORM set_config('request.jwt.claim.sub',owner_id::text,true); PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
  failed:=false; BEGIN UPDATE public.discount_codes SET applicability='selected' WHERE id=c.id; EXCEPTION WHEN check_violation THEN failed:=true; END;
  ASSERT failed, 'Empty selected scope denied'; checks:=checks+1;
  failed:=false; BEGIN UPDATE public.discount_codes SET applicability='selected',ticket_type_ids=ARRAY[vip] WHERE id=c.id; EXCEPTION WHEN raise_exception THEN failed:=strpos(SQLERRM,'pertenecer')>0; END;
  ASSERT failed, 'Wrong product catalog denied'; checks:=checks+1;
  UPDATE public.discount_codes SET applicability='selected',ticket_type_ids=ARRAY[admission],vip_reservado_ids=ARRAY[vip] WHERE id=c.id RETURNING * INTO c;
  ASSERT private.discount_rule_error(c,e,'event_ticket',admission,1) IS NULL, 'Selected admission allowed'; checks:=checks+1;
  ASSERT private.discount_rule_error(c,e,'vip_table',vip,1) IS NULL, 'Selected table allowed'; checks:=checks+1;
  ASSERT private.discount_rule_error(c,e,'event_ticket',gen_random_uuid(),1) IS NOT NULL, 'Unselected product denied'; checks:=checks+1;
  PERFORM set_config('request.jwt.claim.sub',stranger::text,true); PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',stranger,'role','authenticated')::text,true);
  EXECUTE 'SET LOCAL ROLE authenticated';
  SELECT * INTO result FROM public.validate_discount_code_for_product(lower(c.code),e,1,admission,NULL); ASSERT result.id=c.id, 'Authenticated admission RPC'; checks:=checks+1;
  SELECT * INTO result FROM public.validate_discount_code_for_product(c.code,e,1,NULL,vip); ASSERT result.id=c.id, 'Authenticated VIP RPC'; checks:=checks+1;
  failed:=false; BEGIN PERFORM public.validate_discount_code(c.code,e,1); EXCEPTION WHEN raise_exception THEN failed:=strpos(SQLERRM,'no se aplica')>0; END;
  ASSERT failed, 'Legacy client cannot ignore selection'; checks:=checks+1;
  failed:=false; BEGIN PERFORM public.validate_discount_code_for_product(c.code,e,1,admission,vip); EXCEPTION WHEN raise_exception THEN failed:=strpos(SQLERRM,'Solicitud')>0; END;
  ASSERT failed, 'Two product IDs denied'; checks:=checks+1;
  failed:=false; BEGIN PERFORM public.validate_discount_code_for_product(c.code,e,6,NULL,vip); EXCEPTION WHEN raise_exception THEN failed:=strpos(SQLERRM,'Cantidad')>0; END;
  ASSERT failed, 'VIP capacity cannot count as six coupon units'; checks:=checks+1;
  EXECUTE 'RESET ROLE';
  c.min_tickets:=2; ASSERT private.discount_rule_error(c,e,'vip_table',vip,1) IS NOT NULL, 'Minimum units checked'; checks:=checks+1;
  c.min_tickets:=1; c.valid_until:=now()-interval '1 second'; ASSERT private.discount_rule_error(c,e,'event_ticket',admission,1) IS NOT NULL, 'Expired denied'; checks:=checks+1;
  c.valid_until:=NULL; c.valid_from:=now()+interval '1 day'; ASSERT private.discount_rule_error(c,e,'event_ticket',admission,1) IS NOT NULL, 'Future denied'; checks:=checks+1;
  c.valid_from:=now()-interval '1 hour'; c.max_uses:=1; c.uses_count:=1; ASSERT private.discount_rule_error(c,e,'event_ticket',admission,1) IS NOT NULL, 'Exhausted denied'; checks:=checks+1;
  c.max_uses:=NULL; c.uses_count:=0; c.is_active:=false; ASSERT private.discount_rule_error(c,e,'event_ticket',admission,1) IS NOT NULL, 'Inactive denied'; checks:=checks+1;
  tx.kind:='vip_table'; tx.metadata:=jsonb_build_object('event_id',e,'vip_reservado_id',vip,'discount_code_id',c.id,'original_total_cents',30000,'discount_amount_cents',6000,'quantity',1);
  ASSERT private.payment_discount_failure(tx) IS NULL, 'Authoritative percentage amount checked'; checks:=checks+1;
  tx.metadata:=jsonb_set(tx.metadata,'{discount_amount_cents}','29000'); ASSERT private.payment_discount_failure(tx)='discount_changed', 'Tampered discount rejected at fulfillment'; checks:=checks+1;
  tx.metadata:=jsonb_build_object('discount_amount_cents',100); ASSERT private.payment_discount_failure(tx)='discount_missing', 'Amount without code denied'; checks:=checks+1;
  tx.metadata:='{}'; ASSERT private.payment_discount_failure(tx) IS NULL, 'No-discount path unchanged'; checks:=checks+1;
  PERFORM set_config('request.jwt.claim.sub',owner_id::text,true); PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
  UPDATE public.discount_codes SET applicability='all',ticket_type_ids='{}',vip_reservado_ids='{}',discount_type='fixed',discount_value=20 WHERE id=c.id RETURNING * INTO c;
  tx.metadata:=jsonb_build_object('event_id',e,'vip_reservado_id',vip,'discount_code_id',c.id,'original_total_cents',1000,'discount_amount_cents',1000,'quantity',1);
  ASSERT private.payment_discount_failure(tx) IS NULL, 'Fixed discount capped at subtotal'; checks:=checks+1;
  tx.metadata:=jsonb_set(tx.metadata,'{original_total_cents}','30000'); tx.metadata:=jsonb_set(tx.metadata,'{discount_amount_cents}','2000');
  ASSERT private.payment_discount_failure(tx) IS NULL, 'Fixed discount once per table'; checks:=checks+1;
  ASSERT NOT has_function_privilege('authenticated','private.payment_discount_failure(public.payment_transactions)','EXECUTE'), 'Internal payment check protected'; checks:=checks+1;
  ASSERT NOT has_function_privilege('authenticated','private.fulfill_primary_card(text,uuid)','EXECUTE') AND NOT has_function_privilege('authenticated','private.fulfill_vip_card(text,uuid)','EXECUTE'), 'Fulfillment remains private'; checks:=checks+1;
  ASSERT NOT has_function_privilege('anon','public.validate_discount_code_for_product(text,uuid,integer,uuid,uuid)','EXECUTE'), 'Anonymous execute revoked'; checks:=checks+1;
  RAISE EXCEPTION USING ERRCODE='ZQ001', MESSAGE='ROLLBACK_QA_ONLY';
 EXCEPTION WHEN SQLSTATE 'ZQ001' THEN NULL;
 END;
 ASSERT (SELECT count(*) FROM public.discount_codes)=original_codes, 'No coupon residue'; checks:=checks+1;
 ASSERT NOT EXISTS(SELECT 1 FROM notification_private.deliveries), 'No external-delivery work created'; checks:=checks+1;
 PERFORM set_config('eclipse.qa.discount_candidate',jsonb_build_object('passed',checks,'rolled_back',true,'real_payments',false,'real_notifications',false)::text,true);
END $qa$;
SELECT current_setting('eclipse.qa.discount_candidate')::jsonb AS discount_candidate_checks;
ROLLBACK;
