-- Staging-only smoke: random synthetic users, no provider HTTP, all writes rolled back.
begin;
set local statement_timeout='20s';
do $$
declare
 u1 uuid:=gen_random_uuid(); u2 uuid:=gen_random_uuid();
 s1 uuid:=gen_random_uuid(); s2 uuid:=gen_random_uuid();
 iid uuid; first_binding uuid; notice uuid; other_notice uuid;
 fake_token text:='ExponentPushToken[qa_'||replace(gen_random_uuid()::text,'-','')||']';
 old_inbox bigint; old_deliveries bigint; old_tokens bigint;
 result jsonb; rejected boolean; checks integer:=0;
begin
 if not exists(select 1 from notification_private.config where singleton and not capture_enabled and not live_delivery_enabled and not allow_all_recipients and cardinality(allowed_recipients)=0)
  or exists(select 1 from notification_private.outbox) or exists(select 1 from notification_private.deliveries)
 then raise exception 'Smoke requires closed gates and an empty new queue'; end if;
 select count(*) into old_inbox from public.notifications;
 select count(*) into old_deliveries from public.notification_deliveries;
 select count(*) into old_tokens from public.user_push_tokens;
 insert into auth.users(id,email,email_confirmed_at) values
  (u1,'qa-notifications-'||u1||'@example.invalid',now()),(u2,'qa-notifications-'||u2||'@example.invalid',now());
 insert into public.profiles(id,role) values(u1,'attendee'),(u2,'attendee') on conflict(id) do nothing;
 insert into auth.sessions(id,user_id) values(s1,u1),(s2,u2);
 perform notification_private.emit(u1,'attendee','operation.fixture','disabled','Fixture','No delivery','{}','operation');
 if exists(select 1 from notification_private.outbox) then raise exception 'Disabled capture wrote an outbox row'; end if; checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u1,'session_id',s1,'role','authenticated')::text,true);
 set local role authenticated;
 iid:=public.register_notification_installation_v2(null,u1,fake_token,'android','42ebb6eb-62b1-4784-a483-831ae3c804f2');
 reset role;
 select binding_id into first_binding from notification_private.installations where installation_id=iid and user_id=u1 and session_id=s1 and active;
 if first_binding is null then raise exception 'Session-bound installation not registered'; end if; checks:=checks+1;
 -- A future reminder cutover prevents touching existing events while the synthetic outbox is exercised.
 update notification_private.config set capture_enabled=true,cutover_at=now()+interval '1 hour' where singleton;
 perform notification_private.emit(u1,'attendee','operation.fixture','smoke-own','Fixture','No provider delivery','{}','operation');
 perform notification_private.emit(u1,'attendee','operation.fixture','smoke-own','Fixture','No provider delivery','{}','operation');
 perform notification_private.emit(u2,'attendee','operation.fixture','smoke-other','Fixture','No provider delivery','{}','operation');
 if (select count(*) from notification_private.outbox)<>2 then raise exception 'Business deduplication failed'; end if; checks:=checks+1;
 result:=public.prepare_notifications_v2(100);
 if (result->>'prepared')::integer<>2 then raise exception 'Preparation did not create exactly two notices'; end if; checks:=checks+1;
 if (select count(*) from public.notification_deliveries)<>old_deliveries then raise exception 'Legacy queue was touched'; end if; checks:=checks+1;
 if (select count(*) from notification_private.deliveries)<>3 then raise exception 'Expected one device delivery and two emails'; end if; checks:=checks+1;
 if exists(select 1 from public.claim_notification_deliveries_v2()) then raise exception 'Closed live gate allowed a lease'; end if; checks:=checks+1;
 select id into notice from public.notifications where user_id=u1 and delivery_version=2;
 select id into other_notice from public.notifications where user_id=u2 and delivery_version=2;
 set local role authenticated;
 result:=public.notification_inbox_v2();
 if jsonb_array_length(result->'items')<>1 or (result->>'unread_count')::integer<>1 then raise exception 'Own inbox or count incorrect'; end if; checks:=checks+1;
 if exists(select 1 from public.notifications where id=other_notice) then raise exception 'RLS exposed another user notice'; end if; checks:=checks+1;
 if public.notification_detail_v2(other_notice) is not null then raise exception 'Detail leaked cross-user data'; end if; checks:=checks+1;
 if public.notification_destination_v2(other_notice) is not null then raise exception 'Destination leaked cross-user data'; end if; checks:=checks+1;
 if public.notification_inbox_action_v2('read',array[notice],'attendee',u1)<>1 then raise exception 'Read action failed'; end if; checks:=checks+1;
 rejected:=false;
 begin update public.notifications set title='Tampered' where id=notice;
 exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'Message content update was allowed'; end if; checks:=checks+1;
 perform public.notification_preferences_v2_get('attendee');
 update public.notification_preferences_v2 set operations=false where user_id=u1 and role='attendee';
 if not exists(select 1 from public.notification_preferences_v2 where user_id=u1 and role='attendee' and not operations) then raise exception 'Own preferences failed'; end if; checks:=checks+1;
 rejected:=false;
 begin perform public.notification_preferences_v2_get('admin');
 exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'Attendee gained admin preferences'; end if; checks:=checks+1;
 rejected:=false;
 begin perform public.notification_health_v2();
 exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'Attendee gained admin health'; end if; checks:=checks+1;
 rejected:=false;
 begin perform public.claim_notification_deliveries_v2();
 exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'Client invoked delivery worker'; end if; checks:=checks+1;
 rejected:=false;
 begin perform 1 from notification_private.installations;
 exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'Client read private tokens'; end if; checks:=checks+1;
 reset role;
 if exists(select 1 from notification_private.deliveries where status<>'pending' or attempts<>0) then raise exception 'Inbox read changed delivery state'; end if; checks:=checks+1;
 if not exists(select 1 from public.notifications where id=notice and read and read_at is not null and status='sent') then raise exception 'Read and transport states mixed'; end if; checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u2,'session_id',s2,'role','authenticated')::text,true);
 set local role authenticated;
 perform public.register_notification_installation_v2(iid,u2,fake_token,'android','42ebb6eb-62b1-4784-a483-831ae3c804f2');
 result:=public.notification_inbox_v2();
 if jsonb_array_length(result->'items')<>1 or public.notification_detail_v2(notice) is not null then raise exception 'Account switch exposed previous inbox'; end if; checks:=checks+1;
 reset role;
 if not exists(select 1 from notification_private.installations where installation_id=iid and user_id=u2 and session_id=s2 and binding_id<>first_binding) then raise exception 'Account switch failed to rotate binding'; end if; checks:=checks+1;
 set local role authenticated;
 perform public.unregister_notification_installation_v2(iid,u2);
 reset role;
 if exists(select 1 from notification_private.installations where installation_id=iid and active) then raise exception 'Logout failed to unlink'; end if; checks:=checks+1;
 update auth.sessions set not_after=now()-interval '1 minute' where id=s2;
 set local role authenticated;
 rejected:=false;
 begin perform public.register_notification_installation_v2(iid,u2,fake_token,'android','42ebb6eb-62b1-4784-a483-831ae3c804f2');
 exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'Expired session registered a token'; end if; checks:=checks+1;
 reset role;
 if (select count(*) from public.notifications)<>old_inbox+2 or (select count(*) from public.notification_deliveries)<>old_deliveries or (select count(*) from public.user_push_tokens)<>old_tokens then raise exception 'Unexpected legacy changes'; end if; checks:=checks+1;
 if has_function_privilege('anon','public.notification_inbox_v2(text,boolean,timestamp with time zone,uuid,integer,text)','EXECUTE') then raise exception 'Anonymous access to inbox RPC'; end if; checks:=checks+1;
 perform set_config('eclipse.notification_smoke_result',jsonb_build_object('passed',checks,'external_sends',0,'synthetic_users',2,'rollback_required',true)::text,true);
end $$;
select current_setting('eclipse.notification_smoke_result')::jsonb as staging_smoke;
rollback;
