// Reproducible platform exports of the checked-in Eclipse sculptural artwork.
// The original PNGs are immutable inputs; this script never calls an image API.
import { createCanvas, GlobalFonts, loadImage } from '@napi-rs/canvas';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import ts from 'typescript';
import { resolve } from 'node:path';
GlobalFonts.registerFromPath('assets/wallet-pass/fonts/DejaVuSans.ttf', 'Wallet Sans');
GlobalFonts.registerFromPath('assets/wallet-pass/fonts/DejaVuSans-Bold.ttf', 'Wallet Sans');
const out = resolve('assets/wallet-pass');
mkdirSync(out, { recursive: true });
const { outputText } = ts.transpileModule(readFileSync('supabase/functions/_shared/walletDesign.ts','utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext } });
const { WALLET_THEMES: themes } = await import(`data:text/javascript;base64,${Buffer.from(outputText).toString('base64')}`);
const originals = Object.fromEntries(await Promise.all(Object.keys(themes).map(async tier => [tier, await loadImage(`${out}/artwork-v2/${tier}.png`)])));
const bundle = {};
function save(c, name) { const b=c.toBuffer('image/png'); writeFileSync(`${out}/${name}`,b); return b.toString('base64'); }
function art(w,h,tier,platform) {
 const c=createCanvas(w,h), x=c.getContext('2d'); const {background:bg,accent,label}=themes[tier];
 const source=originals[tier];
 x.fillStyle=bg; x.fillRect(0,0,w,h);
 x.imageSmoothingEnabled=true; x.imageSmoothingQuality='high';
 if(platform==='google') {
  // 1032:812 composition, with ~20dp vertical breathing room. No baked text.
  // Crop the deliberately empty left edge, not the sculpture's silhouette.
  const sh=source.height, sw=source.width*.84, sx=source.width-sw;
  const scale=Math.min(w/sw,(h-w*.11)/sh);
  const dw=sw*scale,dh=sh*scale;
  x.drawImage(source,sx,0,sw,sh,(w-dw)/2,(h-dh)/2,dw,dh);
  const fade=x.createLinearGradient(0,0,0,h);
  fade.addColorStop(0,bg);fade.addColorStop(.11,bg+'00');fade.addColorStop(.85,bg+'00');fade.addColorStop(1,bg);
  x.fillStyle=fade; x.fillRect(0,0,w,h);
 } else {
  // Apple event-ticket strip: a wide editorial wordmark and a macro sculpture.
  // Ticket data stays in native fields BELOW the strip, including the category.
  const sw=source.width*.80, sh=source.height*.90;
  const dh=h*1.32, dw=sw/sh*dh;
  x.drawImage(source,source.width-sw,source.height*.035,sw,sh,w-dw,-h*.16,dw,dh);
  const fade=x.createLinearGradient(0,0,w,0);
  fade.addColorStop(0,bg);fade.addColorStop(.43,bg);fade.addColorStop(.67,bg+'00');fade.addColorStop(1,bg+'00');
  x.fillStyle=fade;x.fillRect(0,0,w,h);
  x.save();
  const size=h*.78;
  x.font=`900 ${size}px "Wallet Sans"`;
  const maxWidth=w*(tier==='vip'?.34:.60);
  const squeeze=Math.min(.76,maxWidth/x.measureText(label).width);
  x.translate(w*.035,h*.80);x.scale(squeeze,1);
  x.fillStyle=accent;x.fillText(label,0,0);
  x.restore();
  x.fillStyle=accent+'65';x.fillRect(w*.04,h*.90,w*.22,Math.max(1,h*.008));
 }
 return c;
}
function mark(x,s,accent='#D7C9FF'){x.strokeStyle=accent;x.lineWidth=s*.085;x.beginPath();x.arc(s*.5,s*.5,s*.30,.35,5.8);x.stroke();x.fillStyle='#FFFFFF';x.beginPath();x.arc(s*.77,s*.27,s*.065,0,Math.PI*2);x.fill();}
for(const tier of Object.keys(themes)){
 for(let scale=1;scale<=3;scale++){const suffix=scale===1?'':`@${scale}x`;bundle[`strip_${tier}${suffix}.png`]=save(art(375*scale,98*scale,tier,'apple'),`strip_${tier}${suffix}.png`);}
 save(art(1032,812,tier,'google'),`google_${tier}.png`);
}
for(let scale=1;scale<=3;scale++){
 const suffix=scale===1?'':`@${scale}x`;
 const icon=createCanvas(29*scale,29*scale);mark(icon.getContext('2d'),29*scale);bundle[`icon${suffix}.png`]=save(icon,`icon${suffix}.png`);
 const logo=createCanvas(132*scale,32*scale),x=logo.getContext('2d');mark(x,30*scale);x.fillStyle='#FFFFFF';x.font=`600 ${19*scale}px "Wallet Sans"`;x.textBaseline='middle';x.fillText('ECLIPSE',36*scale,16*scale);bundle[`logo${suffix}.png`]=save(logo,`logo${suffix}.png`);
}
const googleLogo=createCanvas(660,660),gl=googleLogo.getContext('2d');gl.fillStyle='#111020';gl.fillRect(0,0,660,660);mark(gl,660);save(googleLogo,'google_logo.png');
const aliases={BUNDLED_ICON_PNG_BASE64:'icon.png',BUNDLED_LOGO_PNG_BASE64:'logo.png',BUNDLED_FOOTER_PNG_BASE64:'logo.png',BUNDLED_STRIP_PNG_BASE64_GENERAL:'strip_general.png',BUNDLED_STRIP_PNG_BASE64_VIP:'strip_vip.png',BUNDLED_STRIP_PNG_BASE64_BACKSTAGE:'strip_backstage.png',BUNDLED_STRIP_PNG_BASE64_FASTLANE:'strip_fastlane.png'};
writeFileSync('supabase/functions/apple-wallet-generator/bundledAssets.ts','// Generated by scripts/generate_eclipse_wallet_assets.mjs\nexport const WALLET_ASSETS: Record<string,string> = '+JSON.stringify(bundle)+';\n'+Object.entries(aliases).map(([k,v])=>`export const ${k} = WALLET_ASSETS['${v}'];`).join('\n')+'\n');
console.log('Generated native 1x/2x/3x artwork and Google hero images.');
