// Deterministic Eclipse artwork. Native Wallet fields carry all ticket information.
import { createCanvas, GlobalFonts } from '@napi-rs/canvas';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
GlobalFonts.registerFromPath('assets/wallet-pass/fonts/DejaVuSans.ttf', 'Wallet Sans');
GlobalFonts.registerFromPath('assets/wallet-pass/fonts/DejaVuSans-Bold.ttf', 'Wallet Sans');
const out = resolve('assets/wallet-pass');
mkdirSync(out, { recursive: true });
const themes = { general: ['#111020','#BDA9FF'], vip: ['#19150F','#E8C58B'], backstage: ['#17101C','#EAA9DE'], fastlane: ['#0C1B20','#91E4D5'] };
const bundle = {};
function save(c, name) { const b=c.toBuffer('image/png'); writeFileSync(`${out}/${name}`,b); return b.toString('base64'); }
function art(w,h,tier) {
 const c=createCanvas(w,h), x=c.getContext('2d'); const [bg,accent]=themes[tier];
 x.fillStyle=bg; x.fillRect(0,0,w,h);
 const cx=w*.82,cy=h*.45,r=h*.69;
 const glow=x.createRadialGradient(cx,cy,r*.7,cx,cy,r*1.65);
 glow.addColorStop(0,accent+'65');glow.addColorStop(.6,accent+'18');glow.addColorStop(1,accent+'00');
 x.fillStyle=glow;x.fillRect(0,0,w,h);
 for(let i=0;i<7;i++){ x.beginPath();x.ellipse(cx,cy,r*(1+i*.09),r*(.48+i*.035),-.45,0,Math.PI*2);x.strokeStyle=accent+(i===0?'B0':'25');x.lineWidth=Math.max(1,w/750);x.stroke(); }
 const sphere=x.createLinearGradient(cx-r,cy-r,cx+r,cy+r);sphere.addColorStop(0,accent);sphere.addColorStop(.18,bg);sphere.addColorStop(1,'#08090F');
 x.beginPath();x.arc(cx,cy,r*.78,0,Math.PI*2);x.fillStyle=sphere;x.fill();
 x.strokeStyle=accent+'AA';x.lineWidth=w/600;x.beginPath();x.arc(cx,cy,r*.78,Math.PI*.9,Math.PI*1.65);x.stroke();
 // Keep the text zone dark even when Wallet wraps a long event title.
 const fade=x.createLinearGradient(0,0,w,0);fade.addColorStop(0,bg);fade.addColorStop(.50,bg+'F5');fade.addColorStop(.8,bg+'50');fade.addColorStop(1,bg+'20');x.fillStyle=fade;x.fillRect(0,0,w,h);
 return c;
}
function mark(x,s,accent='#D7C9FF'){x.strokeStyle=accent;x.lineWidth=s*.085;x.beginPath();x.arc(s*.5,s*.5,s*.30,.35,5.8);x.stroke();x.fillStyle='#FFFFFF';x.beginPath();x.arc(s*.77,s*.27,s*.065,0,Math.PI*2);x.fill();}
for(const tier of Object.keys(themes)){
 for(let scale=1;scale<=3;scale++){const suffix=scale===1?'':`@${scale}x`;bundle[`strip_${tier}${suffix}.png`]=save(art(375*scale,98*scale,tier),`strip_${tier}${suffix}.png`);}
 save(art(1032,336,tier),`google_${tier}.png`);
}
for(let scale=1;scale<=3;scale++){
 const suffix=scale===1?'':`@${scale}x`;
 const icon=createCanvas(29*scale,29*scale);mark(icon.getContext('2d'),29*scale);bundle[`icon${suffix}.png`]=save(icon,`icon${suffix}.png`);
 const logo=createCanvas(132*scale,32*scale),x=logo.getContext('2d');mark(x,30*scale);x.fillStyle='#FFFFFF';x.font=`600 ${19*scale}px "Wallet Sans"`;x.textBaseline='middle';x.fillText('ECLIPSE',36*scale,16*scale);bundle[`logo${suffix}.png`]=save(logo,`logo${suffix}.png`);
}
const googleLogo=createCanvas(660,660),gl=googleLogo.getContext('2d');gl.fillStyle='#111020';gl.fillRect(0,0,660,660);mark(gl,660);save(googleLogo,'google_logo.png');
const aliases={BUNDLED_ICON_PNG_BASE64:'icon.png',BUNDLED_LOGO_PNG_BASE64:'logo.png',BUNDLED_FOOTER_PNG_BASE64:'logo.png',BUNDLED_STRIP_PNG_BASE64_GENERAL:'strip_general.png',BUNDLED_STRIP_PNG_BASE64_VIP:'strip_vip.png',BUNDLED_STRIP_PNG_BASE64_BACKSTAGE:'strip_backstage.png',BUNDLED_STRIP_PNG_BASE64_FASTLANE:'strip_fastlane.png'};
writeFileSync('supabase/functions/apple-wallet-generator/bundledAssets.ts','// Generated by scripts/generate_eclipse_wallet_assets.mjs\nexport const WALLET_ASSETS: Record<string,string> = '+JSON.stringify(bundle)+';\n'+Object.entries(aliases).map(([k,v])=>`export const ${k} = WALLET_ASSETS['${v}'];`).join('\n')+'\n');
console.log('Generated native 1x/2x/3x artwork and Google hero images.');
