import { drawEclipseArt } from './walletArtwork.mjs';
// Reproducible platform exports of the checked-in Eclipse sculptural artwork.
// The original PNGs are immutable inputs; this script never calls an image API.
import { createCanvas, GlobalFonts, loadImage } from '@napi-rs/canvas';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import ts from 'typescript';
import { resolve } from 'node:path';
GlobalFonts.registerFromPath('assets/wallet-pass/fonts/DejaVuSans.ttf', 'Wallet Sans');
GlobalFonts.registerFromPath('assets/wallet-pass/fonts/DejaVuSans-Bold.ttf', 'Wallet Sans');
const out = resolve('assets/wallet-pass');
mkdirSync(out, { recursive: true });
const { outputText } = ts.transpileModule(readFileSync('supabase/functions/_shared/walletDesign.ts','utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext } });
const { WALLET_THEMES: themes } = await import(`data:text/javascript;base64,${Buffer.from(outputText).toString('base64')}`);
const bundle = {};
function save(c, name) { const b=c.toBuffer('image/png'); writeFileSync(`${out}/${name}`,b); return b.toString('base64'); }
function art(w,h,tier,platform) {
 const c=createCanvas(w,h);drawEclipseArt(c.getContext('2d'),w,h,tier,themes[tier],platform);return c;
}
function mark(x,s,accent='#D7C9FF'){x.strokeStyle=accent;x.lineWidth=s*.085;x.beginPath();x.arc(s*.5,s*.5,s*.30,.35,5.8);x.stroke();x.fillStyle='#FFFFFF';x.beginPath();x.arc(s*.77,s*.27,s*.065,0,Math.PI*2);x.fill();}
for(const tier of Object.keys(themes)){
 for(let scale=1;scale<=3;scale++){const suffix=scale===1?'':`@${scale}x`;bundle[`strip_${tier}${suffix}.png`]=save(art(375*scale,98*scale,tier,'apple'),`strip_${tier}${suffix}.png`);}
 save(art(1032,812,tier,'google'),`google_${tier}.png`);
 save(art(1200,600,tier,'apple'),`card_${tier}.png`);
}
for(let scale=1;scale<=3;scale++){
 const suffix=scale===1?'':`@${scale}x`;
 const icon=createCanvas(29*scale,29*scale);mark(icon.getContext('2d'),29*scale);bundle[`icon${suffix}.png`]=save(icon,`icon${suffix}.png`);
 const logo=createCanvas(132*scale,32*scale),x=logo.getContext('2d');mark(x,30*scale);x.fillStyle='#FFFFFF';x.font=`600 ${19*scale}px "Wallet Sans"`;x.textBaseline='middle';x.fillText('ECLIPSE',36*scale,16*scale);bundle[`logo${suffix}.png`]=save(logo,`logo${suffix}.png`);
}
const googleLogo=createCanvas(660,660),gl=googleLogo.getContext('2d');gl.fillStyle='#111020';gl.fillRect(0,0,660,660);mark(gl,660);save(googleLogo,'google_logo.png');
const aliases={BUNDLED_ICON_PNG_BASE64:'icon.png',BUNDLED_LOGO_PNG_BASE64:'logo.png',BUNDLED_FOOTER_PNG_BASE64:'logo.png',BUNDLED_STRIP_PNG_BASE64_GENERAL:'strip_general.png',BUNDLED_STRIP_PNG_BASE64_VIP:'strip_vip.png',BUNDLED_STRIP_PNG_BASE64_BACKSTAGE:'strip_backstage.png',BUNDLED_STRIP_PNG_BASE64_FASTLANE:'strip_fastlane.png'};
writeFileSync('supabase/functions/apple-wallet-generator/bundledAssets.ts','// Generated by scripts/generate_eclipse_wallet_assets.mjs\nexport const WALLET_ASSETS: Record<string,string> = '+JSON.stringify(bundle)+';\n'+Object.entries(aliases).map(([k,v])=>`export const ${k} = WALLET_ASSETS['${v}'];`).join('\n')+'\n');
console.log('Generated native 1x/2x/3x artwork and Google hero images.');
